import { AxiogramBase, baseAxiograms } from './axiogram-base';
import { World } from './world';

export interface Axiogram {
  axiogramBase: AxiogramBase;
  phrase: string;
  excerpt: string;
  explanation: string;
  plus: string;
  zero: string;
  minus: string;
}

type AxiogramTextData = [string, string, string, string, string, string];

const me: AxiogramTextData[] = [
  ['Una buena comida', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA TOMAR LO NECESARIO EN EL CUMPLIMENTO DE LAS TAREAS PRÁCTICAS.', 'Representa la acción de tomar cosas buenas para el funcionamiento vital y facilitar la acción práctica en el mundo.', 'Si se sobrevalora (1 al 5) puede reflejar tendencia al hedonismo.', 'Toma lo justo, ni más ni menos.', 'Si se devalora (7 al 9) la persona es modesta y no toma lo suficiente.'],
  ['Un mejoramiento técnico', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA TOMAR INICIATIVAS Y MEJORAR PROCEDIMIENTOS Y HERRAMIENTAS DENTRO LOS SISTEMAS Y ORGANIZACIONES.', 'Representa agregar valorar a los medios, las técnicas, los objetos y los procedimientos dentro del sistema.', 'Si se sobrevalora (2 a 8), la persona tiene mucha iniciativa.', '(n/a)', 'Si se distorsiona (10 al 18) hay despreocupación y negligencia con los procedimientos y las técnicas.'],
  ['Una idea absurda', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RECONOCER IDEAS SIN SENTIDO Y CARENTES DE UTILIDAD.', 'Se trata de lo irracional y arbitrario que no tiene sentido ni lleva a ningún lado.', 'Si se sobrevalora (11 al 18), hay rigidez, miedo a perder el control.', '(n/a)', 'Si se distorsiona (1 al 9) la persona carece de lógica tiende a la extravagancia simplona.'],
  ['Una multa', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RECONOCER Y ASUMIR LAS CONSECUENCIAS NEGATIVAS DE SUS ERRORES.', 'Representa una penalización del sistema por errores o reglas que se rompen.', 'Cuando el axiograma es sobrevalorado (12 al 18) la persona no acepta las consecuencias de sus faltas.', '(n/a)', 'Si la persona distorsiona este axiograma (1 al 9) busca ser castigado.'],
  ['Basura', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RECONOCER CUANDO ALGO HA PERDIDO UTILIDAD Y REQUIERE SER DESECHADO.', 'Representa los desechos, lo inservible y que ha perdido sus componentes funcionales.', 'Cuando está sobrevalorado (14 al 18) la persona tiene obsesión por lo puro, lo limpio y lo ordenado.', '(n/a)', 'Si se desvalora (12 al 10) a la persona le cuesta distinguir lo desechable.'],
  ['Un científico dedicado', 'EVALUA LA CAPACIDAD DE LA PERSONA DE VALORAR A LOS DEMÁS POR LA FUNCIÓN Y MISIÓN QUE TIENEN EN EL MUNDO.', 'Significa el valor de la dedicación de la existencia humana a una función socialmente significativa.', 'Si se sobrevalora (1 al 4) se idealiza a la persona por su rol.', '(n/a)', 'Si se desvalora (6 al 9) se tiene desconfianza de las profesiones de las personas.'],
  ['Hacer estallar un avión en vuelo con pasajeros dentro', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA DISTINGUIR EL MAL EN USAR LOS MEDIOS MATERIALES PARA DESTRUIR LA EXISTENCIA.', 'Aquí los medios y procedimientos materiales son pensados para la destrucción de la vida.', 'Cuando a este axiograma se le asigna el valor 18, la persona considera que es peor matar a un grupo de personas.', '(n/a)', 'Si este axiograma se distorsiona (9 al 1) la persona usa deliberadamente los medios para engañar a los demás.'],
  ['Quemar a un hereje en una hoguera', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RESPETAR EL DERECHO DE LOS OTROS A DISENTIR Y NO ADHERIRSE A UN SISTEMA Y/O CREENCIA.', 'Representa la pena máxima, humillante y dolorosa para las personas que disienten de las normas.', 'Si se sobrevalora (17 o 18) la persona detesta que los demás sean perseguidos por sus ideas.', '(n/a)', 'Si se distorsiona (del 9 al 1) refleja sadismo al aprobar métodos para la destrucción de la vida.'],
  ['Un cortocircuito', 'EVALUA LA CAPACIDAD DE LA PERSONA PARA RECONOCER LA TEMPORALIDAD Y LOS CAMBIOS DEL APOYO DEL SISTEMA AL PROPIO DESEMPEÑO O CRECIMIENTO.', 'El sistema eléctrico interrumpe el suministro temporal de energía.', 'Si sobrevalora (del 13 al 18) se niega a aceptar la pérdida del apoyo.', '(n/a)', 'Si distorsiona (9 al 1) la persona considera positivo no recibir apoyo del sistema.'],
  ['Con este anillo yo te desposo', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA ESTABLECER VÍNCULOS DE COMPROMISO Y CUMPLIR CON SU PALABRA.', 'El anillo es un símbolo del compromiso en general y del compromiso intimo afectivo.', 'Cuando la persona sobrevalora el compromiso asigna un número menor a este axiograma (1, 2 o 3).', '(n/a)', 'Cuando el valor está distorsionando (asignando del 10 al 18) la persona tiende a engañar a las personas.'],
  ['Un bebé', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RECONOCER EL VALOR FUNDAMENTAL DE LOS DEMÁS.', 'Representa la existencia humana viniendo dentro de la no existencia.', 'No es posible sobrevalorarlo.', '(n/a)', 'Su valor axiológico es (1), si la persona asigna un valor mayor le resta valor a la vida humana.'],
  ['Torturar a una persona', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RECONOCER EL MAL IMPLICADO EN DESTRUIR CONSTANTEMENTE Y DE FORMA SÁDICA LA EXISTENCIA HUMANA.', 'Torturar es un acto perpetuo de sadismo y crueldad contra una persona.', 'No es posible sobrevalorarlo.', '(n/a)', 'Si se quita disvalor al disvalor (17-10) la persona tiende a relaciones donde se permite cierto grado de maltrato.'],
  ['Amor a la naturaleza', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA APRECIAR EL ORDEN Y LA FUNCIÓN PRÁCTICA DE LOS OBJETOS.', 'La naturaleza es la totalidad de todas las cosas y es valorada intrínsecamente.', 'Cuando se sobrevolara asignándole el número 1, se tiene tendencia a cosificar.', '(n/a)', 'Cuando se le resta valor (3 al 9) la persona es débil en captar el orden.'],
  ['Un loco', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA COMPRENDER LAS IDEAS DE OTROS ES LA CAPACIDAD DE EMPATÍA COGNITIVA.', 'Un loco es la persona que ha perdido sus funciones mentales.', 'Si se añade disvalor a este disvalor (del 15 al 18) hay rigidez.', '(n/a)', 'Si se distorsiona (del 1 al 9) la persona considera las ideas de los otros sin ningún valor.'],
  ['Una línea de producción en serie', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA APRECIAR EL TRABAJO EN EQUIPO.', 'Representa el valor del colaboracionismo y del trabajo en equipo.', 'Cuando está sobrevalorado (1 al 7) la persona depende del grupo para actuar.', '(n/a)', 'Si se distorsiona (10 al 18), la persona rechaza el trabajo en equipo.'],
  ['Esclavitud', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA EVITAR RELACIONES DE SOMETIMIENTO Y NO CONSIDERAR LA EXISTENCIA HUMANA UNA MERCANCIA.', 'Representa someter al otro para un beneficio económico o práctico personal.', 'Si se sobrevalora (16-18) la persona necesita mucho espacio.', '(n/a)', 'Cuando este axiograma se distorsiona (9 al 1) se busca ser esclavizado y esclavizar a los demás.'],
  ['Un genio matemático', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA ENTENDER EL ORDEN MAYOR Y LA MISIÓN DE LOS SISTEMAS CON UN SENTIDO DE PERSPECTIVA.', 'Representa el orden perfecto, el modelo con significado, armonía y exactitud.', 'Si se sobrevalora (1, 2) hay obsesión por el orden lógico y el significado.', '(n/a)', 'Si se distorsiona (10 al 18) la persona deliberadamente prefiere el caos al orden.'],
  ['Un uniforme', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RESPETAR FIGURAS DE AUTORIDAD, Y COMPRENDER REGLAS DENTRO DE UN SISTEMA.', 'Representa un símbolo de pertenencia a una organización.', 'Si se sobrevalora (1 al 6) la persona admira las figuras de autoridad.', '(n/a)', 'Si se distorsiona (10 al 18) la persona tiene aversión a las figuras de autoridad.'],
];

const mi: AxiogramTextData[] = [
  ['Me gusta mi trabajo, me hace bien', 'EVALÚA LA CAPACIDAD DE FORMAR VALORES DE SATISFACCIÓN EN TIEMPO REAL RECONOCIENDO LA CONTRIBUCIÓN MEDIANTE LA VOCACIÓN Y ROLES SOCIALES.', 'Representa la apreciación de los pasos y las actividades necesarias para la construcción del rol.', 'Si se sobrevalora (5 al 1), se tiende a la cosificación.', '(n/a)', 'Si distorsiona (10 al 18) prevalece la insatisfacción.'],
  ['El universo es un sistema notablemente armonioso', 'EVALÚA LA CAPACIDAD PARA VALORAR LA PERTENENCIA A UN SISTEMA IDEAL QUE IMPULSA Y MOTIVA LA AUTOREALIZACIÓN.', 'El útero constituye un primer universo de seguridad.', 'Si se sobrevalora (8 al 1) la persona idealiza el yo con metas elevadas e inalcanzables.', '(n/a)', 'Si se distorsiona (10 al 18) hay desconfianza de todos los úteros y decepción de todos los sistemas.'],
  ['El mundo no tiene mucho sentido para mí', 'ES LA CAPACIDAD PARA AUTO EVALUAR LA CONTRIBUCIÓN PERSONAL DENTRO DE SISTEMAS Y GRUPOS CON SIGNIFICADO EXISTENCIAL.', 'Representa una dinámica existencial entre el significado individual y las figuras sistémicas formativas del mundo interior.', 'Si se sobrevalora (11 al 18) hay un sobre enfoque en la auto meta con rigidez y perfeccionismo.', '(n/a)', 'Si se distorsiona (9 al 1) la persona tiene decepción.'],
  ['Por mas intensamente que trabaje siempre me sentiré frustrado', 'EVALUA LA CAPACIDAD COGNITIVA PARA DISTINGUIR IDEAS NEGATIVAS SOBRE EL DESEMPEÑO DEL ROL QUE LLEVAN A LA FRUSTRACION.', 'Devaloración sistémica del rol.', 'Si se sobrevalora (12 al 18), la persona tiene alta tolerancia a la frustración.', '(n/a)', 'Si se distorsiona (9 al 1) la persona exagera los retos convirtiéndolos en obstáculos.'],
  ['Las condiciones en que trabajo son deplorables y arruinan mi trabajo', 'EVALUA LA CAPACIDAD DE FORMAR VALORES PARA DEFENDER LA DIGNIDAD EN LAS ÁREAS DEL DESEMPEÑO DEL ROL.', 'Se trata de personas que son devastadas por el contexto.', 'Si se sobrevalora (14 al 18) a la persona nada la detiene.', '(n/a)', 'Si se distorsiona nada es suficiente.'],
  ['Yo me siento a gusto en el mundo', 'EVALUA LA CAPACIDAD DE LA PERSONA PARA SOSTENER EL VALOR DE SU YO CUANDO SOCIALIZA.', 'Es la capacidad de socializar sosteniendo el valor del yo.', 'Si se sobrevalora (1 al 4) hay pretensión y arrogancia.', '(n/a)', 'Si se distorsiona (10 al 18) la persona rechaza aparecer en lugares públicos.'],
  ['Detesto mi trabajo', 'EVALÚA LA CAPACIDAD PARA FORMAR VALORES QUE IMPIDAN CONSIDERAR EL TRABAJO COMO ALGO DESTRUCTIVO PARA LA SOCIEDAD Y PARA SÍ MISMO.', 'El propio trabajo se considera destructivo para el yo.', 'Si se sobrevalora (18) la persona ofrece lo mejor de sí en sus roles.', '(n/a)', 'Si se distorsiona (1 al 9) la persona ofrece su odio.'],
  ['Mi vida está trastornando al mundo', 'EVALÚA LA CAPACIDAD DE FORMAR VALORES PARA PROYECTAR LA MISIÓN EN EL MUNDO CON MODESTIA, REALISMO.', 'La contribución personal y única que se hace a la sociedad requiere ser auto evaluada.', 'Si se sobrevalora (17 y 18) la persona es cautelosa de asumir responsabilidades grandes.', '(n/a)', 'Si se distorsiona (9 al 1) la persona vive en fantasía con perfil narcisista.'],
  ['Mi trabajo no contribuye con nada al mundo', 'ES LA CAPACIDAD DE AUTOVALORARSE OBJETIVAMENTE EN EL DESPLIEGUE DE LA MISIÓN DE FORMA QUE MOTIVE LA AUTODISCIPLINA.', 'Representa los mensajes actitudinales motivacionales de la madre al hijo(a).', 'Si se sobrevalora (13 al 18) la persona tenderá al perfeccionismo.', '(n/a)', 'Si se distorsiona (1 al 9) la persona cree que es un don nadie.'],
  ['Mi trabajo pone de manifiesto lo mejor que hay en mi', 'EVALUA LA CAPACIDAD DE REALIZAR EL TRABAJO CON VALORES QUE SOSTIENEN EL PROYECTO VITAL PERSONAL.', 'Representa el auto amor y la presencia interior en cada cosa que se realiza.', 'Si se sobrevalora (1 al 3) hay tendencia a la inflación del ego.', '(n/a)', 'Si se distorsiona (10 al 18) la persona desaprueba constantemente su actividad.'],
  ['Estoy contento con ser yo mismo', 'EVALUA LA CAPACIDAD DE LA PERSONA PARA RECONOCER SU PROPIO VALOR Y AUTOAFIRMARSE.', 'Representa la autoaceptación incondicional.', 'Imposible sobrevalorar.', '(n/a)', 'Si hay una distorsión (10 al 18) se presume experiencia de trauma.'],
  ['Maldigo el día en que nací', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA RECONOCER AUTOJUICIOS NEGATIVOS Y EL MAL IMPLICADO EN DENOSTAR LA PROPIA EXISTENCIA.', 'Representa el autoodio derivado del conflicto emocional y psicológico con los padres biológicos.', 'Imposible sobrevalorar.', '(n/a)', 'Si se distorsiona (9 al 1) hay trauma por maltrato psicológico, sexual o físico.'],
  ['Me encanta mi trabajo', 'EVALUA LA CAPACIDAD DE FORMAR JUICIOS POSITIVOS SOBRE EL DESEMPEÑO DE LOS DIFERENTES ROLES.', 'Representa el gozo de la actividad que contribuye a la formación de los roles sociales personales.', 'Si se sobrevalora (con 1) cierta tendencia la cosificación.', '(n/a)', 'Cuando se distorsiona (10 al 18) hay aversión al rol.'],
  ['Me molesta que el universo no tenga sentido', 'EVALÚA LA CAPACIDAD PARA RECONOCER EL DAÑO POR LA PERDIDA DE SIGNIFICADO EXISTENCIAL.', 'La persona no encuentra su lugar en la existencia.', 'Si se sobrevalora (15 al 18) la persona ha perdido la esperanza de que el sentido llegue.', '(n/a)', 'Si se sobrevalora (1 al 9), la persona siente el dolor de la falta de sentido todo el tiempo.'],
  ['Cuanto mejor comprendo mi lugar en el mundo, tanto mejor me va en mi trabajo', 'EVALÚA LA CAPACIDAD DE FORMAR VALORES PARA RECONOCER EL LUGAR Y LA JERARQUÍA CORRESPONDIENTE AL DESEMPEÑO DE LOS ROLES.', 'El primer lugar que se tiene en la vida es de hijo o hija de la madre.', 'Si se sobrevalora (7 al 1) hay protagonismo y ego inflado.', '(n/a)', 'Si se distorsiona (10 al 18), la persona no busca ayuda del sistema.'],
  ['Mi trabajo me hace desdichado', 'EVALÚA LA CAPACIDAD DE LA PERSONA PARA COMPRENDER LAS CONSECUENCIAS NEGATIVAS DEL VICTIMISMO.', 'Representa la incapacidad de la persona de valorar su yo en el trabajo.', 'Si se sobrevalora (16 al 18) la persona pondera la actividad como algo central.', '(n/a)', 'Si distorsiona (9 al 1) la persona sufre en la realización de sus actividades.'],
  ['Amo la belleza del mundo', 'EVALUA LA CAPACIDAD DE FORMAR VALORES PARA DESARROLLAR UN YO IDEAL AL ACEPTAR EL ORIGEN Y PERTENENCIA AL SISTEMA FAMILIAR.', 'Representa la satisfacción del yo en la manifestación de su voluntad existencial.', 'Si se sobrevalora (1 o 2) hay idealización a la madre.', '(n/a)', 'Si se distorsiona (10 al 18) se tuvo una madre o figuras sistémicas primarias hostiles.'],
  ['Mi trabajo contribuye a la belleza y armonía del mundo', 'EVALÚA LA CAPACIDAD DE FORMAR VALORES MOTIVACIONALES PARA DESARROLLAR EL PROYECTO DE VIDA RECONOCIENDO LA CONTRIBUCIÓN AL MUNDO.', 'Representa la convicción de la contribución que se hizo como hijos/as trayendo belleza y riqueza al mundo de la madre.', 'Si se sobrevalora (6 al 1) hay orgullo basado en la idealización de la madre.', '(n/a)', 'Cuando se distorsiona la persona no puede imaginar un yo ideal.'],
];

const ms: AxiogramTextData[] = [
  ['Mi deseo sexual es insaciable', 'EVALUA LA CAPACIDAD DE MANTENER CONEXIÓN CON LA LÍBIDO COMO ENERGÍA VITAL AUN DESPUÉS DEL ACTO SEXUAL.', 'La libido es la energía vital.', 'Si se sobrevalora (5 al 1) tendencia a la adicción sexual.', 'La persona está conectada con su energía vital en su máxima expresión.', 'Si se desvalora (7 al 9) la persona regula su energía sexual con cautela.'],
  ['Mi práctica sexual me hace muy hábil sexualmente', 'ES LA CAPACIDAD DE AUTO EVALUAR EL DESEMPEÑO SEXUAL EN LA TÉCNICA.', 'La persona se auto evalúa positivamente en su desempeño sexual.', 'Si se sobrevalora (8 al 1), la persona idealiza su yo sexual.', 'No hay idealización, ni flojera de aprender más.', 'Si distorsiona (10 al 18), hay pereza sexual.'],
  ['Mi práctica sexual me crea dificultad', 'ES LA CAPACIDAD PARA IDENTIFICAR IDEAS NEGATIVAS DE SI MISMO QUE PUEDAN INHIBIR LA DISPONIBILIDAD PARA EL RITO SEXUAL.', 'Representa auto juicios de desaprobación para el desempeño sexual.', 'Si se sobrevalora (11 al 18) hay perfeccionismo en el desempeño sexual.', '(n/a)', 'Si se distorsiona (1 al 9) la persona tiende a abandonar la sexualidad.'],
  ['Mi habilidad sexual destruye mi deseo sexual', 'EVALÚA LA CAPACIDAD PARA EVITAR AUTO JUCIOS NEGATIVOS SOBRE EL DESEMEÑO SEXUAL QUE APAGUEN EL DESEO SEXUAL.', 'Representa los auto juicios negativos de la persona por su desempeño sexual.', 'Si se sobrevalora (12 al 18) la persona magnifica su destreza sexual.', '(n/a)', 'Si se distorsiona (9 al 1) la persona se denigra a si misma.'],
  ['Mientras más sexual me siento menos me gusta', 'EVALÚA LA CAPACIDAD DE INTEGRAR LA PULSIÓN SEXUAL EN EL DESARROLLO DE LA PERSONALIDAD ASUMIENDO UN ROL SEXUAL COMO ADULTO.', 'Representa el rechazo a asumir el rol sexual.', 'Si se sobrevalora (14 al 18) hay sobre actuación del rol sexual.', 'Mi deseo sexual lo asumo y lo puedo manifestar en mi cuerpo.', 'En distorsión (1 al 9) la persona oculta su sexualidad.'],
  ['La habilidad sexual aumenta mi capacidad para amar', 'ES LA CAPACIDAD DE PONER LAS TÉCNICAS SEXUALES AL SERVICIO DEL AMOR.', 'Representa el reconocimiento del rito sexual mediante la destreza y el éxtasis espiritual.', 'Si se sobrevalora (1 al 4) se idealiza la técnica.', '(n/a)', 'Si se distorsiona (10 al 18) se tiende a la monotonía.'],
  ['Yo detesto mi deseo sexual', 'EVALÚA LA CAPACIDAD PARA FORMAR VALORES QUE IMPIDAN DESPRECIAR EL CUERPO Y EL PROPIO DESEO SEXUAL.', 'Representa estar en contra de la líbido expresada en el deseo erótico.', 'Si sobrevalora (18) vive con deleite su deseo.', 'No tiene ningún rechazo a su propio cuerpo.', 'Si se distorsiona (1 al 9) hay sexo adicción, perversiones y/o parafilias.'],
  ['Yo detesto mi práctica sexual', 'EVALÚA LA CAPACIDAD DE FORMAR VALORES PARA PRESERVAR LA DIGNIDAD DEL YO DURANTE LOS ACTOS SEXUALES.', 'La persona pierde dignidad en los encuentros sexuales.', 'Si se sobrevalora (17 o 18) hay idealización, perfeccionismo y orgullo sexual.', 'No hay ningún tipo de perturbación de mi ser a la sexualidad.', 'Si distorsiona (1 al 9) hay trauma sexual.'],
  ['No me gusta mi práctica sexual', 'ES LA CAPACIDAD PARA AUTOVALORARSE OBJETIVA Y EMPÁTICAMENTE EN EL DESEMPEÑO DEL ROL SEXUAL.', 'Es la valoración negativa del rol sexual.', 'Si se sobrevalora (13 al 18), tendencia al orgullo y perfeccionismo sexual.', '(n/a)', 'Si se distorsiona (1 al 9), la persona siente fracaso personal en su rol sexual.'],
  ['Yo deseo amar y ser amado', 'EVALÚA LA CAPACIDAD DE PONER EL DESEO AL SERVICIO DEL AMOR DURANTE EL ACTO.', 'Representa la unión de la líbido con el afecto.', 'Si se sobrevalora (2 o 3), hay idealización rosa.', 'El deseo está bien colocado en el otro.', 'Si se distorsiona (10 al 18) se rechaza tanto el deseo como el amor.'],
  ['Yo amo amar y ser amado', 'EVALÚA LA CAPACIDAD DE MOSTRAR Y RECIBIR AFECTO TERNURA Y EMPATÍA DURANTE EL ACTO SEXUAL.', 'El amor produce excitación.', 'No es posible sobrevalorarlo.', '(n/a).', 'Si se distorsiona (10 al 18) se rechaza tanto el deseo como el amor.'],
  ['El amor es odioso para mí', 'EVALÚA LA CAPACIDAD PARA RECONOCER EL DAÑO DE LOS ACTOS SEXUALES QUE SE REALIZAN CON ODIO HACIA EL OTRO.', 'El sexo es un lugar para expresar odio.', 'Imposible sobrevalorarlo.', '(n/a)', 'Si se distorsiona (10 al 18) la persona tiene filofobia.'],
  ['Yo amo ser sexualmente deseado', 'EVALÚA LA CAPACIDAD DE SER ACCESIBLE SEXUALMENTE Y ACEPTAR EL DESEO DEL OTRO SOBRE EL PROPIO CUERPO.', 'Es la aceptación del yo para conscientemente exponer el cuerpo como actor sexual.', 'Si se sobrevalora (1) hay cierta idealización.', '(n/a)', 'En distorsión (10 al 18) hay vergüenza del propio cuerpo.'],
  ['El sexo destruye mi amor', 'EVALÚA LA CAPACIDAD PARA VALORAR LA SEXUALIDAD COMO VEHÍCULO DEL AMOR, LA CONEXIÓN Y LA INTIMIDAD.', 'Representa la experiencia de maltrato sexual prematuro.', 'Si se sobrevalora (15 al 18), se toman todas las oportunidades para ejercer la sexualidad.', 'El sexo no tiene porque dañarle a uno.', 'Con distorsión (9 al 1), la persona se cierra a la sexualidad afectiva.'],
  ['Mi habilidad sexual aumenta mi deseo sexual', 'EVALÚA LA CAPACIDAD DE CONECTAR LA TECNICA CON LA LÍBIDO.', 'Representa la capacidad de enriquecer el valor de la sexualidad.', 'Si se sobrevalora (7 al 1) la persona se obsesiona e idealiza la experiencia sexual.', 'Equilibrio entre tecnica y nutrición de su propio deseo.', 'Si se distorsiona (10 al 18) no hay creatividad sexual.'],
  ['El amor no me gusta', 'EVALÚA LA CAPACIDAD PARA IDENTIFICAR CONDUCTAS FILOFÓBICAS.', 'Es la desvaloración del deseo y del cuerpo en relación con el amor.', 'Si se sobrevalora (16 al 18) idealización romántica.', '(n/a)', 'Si se distorsiona (9 al 1) incapacidad de juntar el deseo sexual con el amor.'],
  ['Yo amo el juego sexual', 'EVALÚA LA CREATIVIDAD EN EL PREAMBULO SEXUAL.', 'Representa el aspecto del anima en la sexualidad.', 'Si se sobrevalora (1 o 2) hay sobre enfoque en la seducción.', '(n/a)', 'Si se distorsiona (10 al 18) la persona desconfía de la seducción y la detesta.'],
  ['Mi deseo sexual aumenta mi habilidad sexual', 'EVALÚA LA CAPACIDAD DE INTEGRAR LA LIBIDO A LAS EVOLUCIONES DE TÉCNICAS Y BIONERGETICAS SOBRE LA SEXUALIDAD.', 'Representa el deseo al servicio de la técnica sexual.', 'Si se sobrevalora (6 al 1) la persona exagera el rol masculino en la sexualidad.', 'Equilibrio entre la técnica y su propio deseo.', 'Si se distorsiona (10 al 18) la persona se desconecta de la líbido.'],
];

function buildAxiogramsForWorld(textData: AxiogramTextData[]): Axiogram[] {
  return textData.map((data, i) => ({
    axiogramBase: baseAxiograms.get(i + 1)!,
    phrase: data[0],
    excerpt: data[1],
    explanation: data[2],
    plus: data[3],
    zero: data[4],
    minus: data[5],
  }));
}

export const axiogramsByWorld = new Map<string, Axiogram[]>([
  [World.EXTERNAL, buildAxiogramsForWorld(me)],
  [World.INTERNAL, buildAxiogramsForWorld(mi)],
  [World.SEXUAL, buildAxiogramsForWorld(ms)],
]);
